[package]
name = "bilderna"
version = "0.1.0"
authors = ["AzariasB"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.23.6", default-features = true }
imageproc = "0.22.0"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
lazy_static = "1.4.0"
