[package]
name = "bilderna"
version = "0.2.0"
authors = ["AzariasB"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.7", default-features = true }
imageproc = "0.23.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
lazy_static = "1.4.0"
actix-web = "4"
env_logger = "0.10.0"
chrono = "0.4.28"