[package]
name = "bilderna"
version = "0.2.0"
authors = ["AzariasB"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.23.14", default-features = true }
imageproc = "0.22.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
lazy_static = "1.4.0"
actix-web = "3"
env_logger = "0.8.3"
chrono = "0.4.19"